<a href="https://colab.research.google.com/github/GithubPython7Eduard/Python-Library/blob/main/Copy_of_3_1_Complete_Numpy_Tutorial_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy - Numerical Python

Advantages of Numpy Arrays:

1. Allows several Mathematical Operations
2. Faster operations

In [1]:
import numpy as np

List vs Numpy - Time Taken

In [2]:
from time import process_time

Time taken by a list

In [3]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0019789659999998044


In [4]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5  

end_time = process_time()

print(end_time - start_time)

0.0005394469999999707


Numpy Arrays

In [5]:
# list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [6]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [7]:
# creating a 1 dim array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [8]:
a.shape

(4,)

In [9]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [10]:
b.shape

(2, 4)

In [11]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Placeholders in numpy arrays

In [12]:
# create a numpy array of Zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [13]:
# create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [14]:
# array of a particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [15]:
# create an identity matrix
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [16]:
# create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.5221586  0.75665451 0.31568195 0.60892858]
 [0.08370494 0.69069939 0.25778248 0.7446312 ]
 [0.87562368 0.99656894 0.73354038 0.29298233]]


In [17]:
# random integer values array within a specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[84 83 28 59 39]
 [93 18 58 14 39]
 [42 21 96 68 52]]


In [18]:
# array of evenly spaced values --> specifying the number of values required
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [19]:
# array of evenly spaced values --> specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [20]:
# convert a list to a numpy array
list2 = [10,20,20,20,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

Analysing a numpy array

In [21]:
c = np.random.randint(10,90,(5,5))
print(c)

[[64 58 30 73 85]
 [11 67 71 50 59]
 [38 24 36 25 63]
 [24 46 86 64 86]
 [71 56 77 38 27]]


In [22]:
# array dimension
print(c.shape)

(5, 5)


In [23]:
# number of dimensions
print(c.ndim)

2


In [24]:
# number of elements in an array
print(c.size)

25


In [25]:
# checking the data type of the values in the array
print(c.dtype)

int64


Mathematical operations on a np array

In [26]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2)    # concatenate or joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [27]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [28]:
print(a)
print(b)

[[7 0 9]
 [9 0 9]
 [0 0 5]]
[[12 12 13]
 [16 14 17]
 [14 12 19]]


In [29]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[19 12 22]
 [25 14 26]
 [14 12 24]]
[[ -5 -12  -4]
 [ -7 -14  -8]
 [-14 -12 -14]]
[[ 84   0 117]
 [144   0 153]
 [  0   0  95]]
[[0.58333333 0.         0.69230769]
 [0.5625     0.         0.52941176]
 [0.         0.         0.26315789]]


In [30]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [31]:
print(a)
print(b)

[[8 9 5]
 [2 0 6]
 [7 8 6]]
[[17 11 13]
 [15 12 18]
 [14 10 17]]


In [32]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[25 20 18]
 [17 12 24]
 [21 18 23]]
[[ -9  -2  -8]
 [-13 -12 -12]
 [ -7  -2 -11]]
[[136  99  65]
 [ 30   0 108]
 [ 98  80 102]]
[[0.47058824 0.81818182 0.38461538]
 [0.13333333 0.         0.33333333]
 [0.5        0.8        0.35294118]]


Array Manipulation

In [33]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[1 3 2]
 [2 5 4]]
(2, 3)


In [34]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[1 2]
 [3 5]
 [2 4]]
(3, 2)


In [35]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[7 3 1]
 [4 4 4]]
(2, 3)


In [36]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[7 4]
 [3 4]
 [1 4]]
(3, 2)


In [37]:
# reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[4 8 3]
 [3 7 7]]
(2, 3)


In [38]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[4 8]
 [3 3]
 [7 7]]
(3, 2)
